/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/adminPage/AdminPage': RouteRecordInfo<'/adminPage/AdminPage', '/adminPage/AdminPage', Record<never, never>, Record<never, never>>,
    '/licensePage/LicensePage': RouteRecordInfo<'/licensePage/LicensePage', '/licensePage/LicensePage', Record<never, never>, Record<never, never>>,
    '/loginPage/LoginPage': RouteRecordInfo<'/loginPage/LoginPage', '/loginPage/LoginPage', Record<never, never>, Record<never, never>>,
    '/notFoundPage/NotFoundPage': RouteRecordInfo<'/notFoundPage/NotFoundPage', '/notFoundPage/NotFoundPage', Record<never, never>, Record<never, never>>,
  }
}
